In [1]:
import numpy as np
import array as ar

In [2]:
np.__version__

'1.16.4'

In [3]:
L = list(range(10))
A = ar.array('f', L)
print(A)

array('f', [0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0])


In [4]:
np_array = np.array([range(i, i+5) for i in [0, 0, 0]], dtype = 'float')
print(np_array)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [5]:
np_array_1 = np.zeros(10, dtype = 'int')
np_array_2 = np.zeros((2,3,4), dtype = 'int')
np_array_3 = np.full((2,2), 4/12, dtype = 'float')
np_array_4 = np.arange(0, 20, 4)
np_array_5 = np.linspace(0, 5, 12)
np_array_6 = np.random.random((4, 4))
np_array_7 = np.random.normal(0, 1, (3, 3))
np_array_8 = np.random.randint(20, 25, (3, 3))
np_array_9 = np.eye(5, 5, dtype = 'int')
np_array_10 = np.empty((4, 4))
print('First array \n', np_array_1)
print('Second array \n', np_array_2)
print('Third array \n', np_array_3)
print('Fourth array \n', np_array_4)
print('Fifth array \n', np_array_5)
print('Sixth array \n', np_array_6)
print('Seventh array \n', np_array_7)
print('Eighth array \n', np_array_8)
print('Ninth array \n', np_array_9)
print('Tenth array \n', np_array_10)

First array 
 [0 0 0 0 0 0 0 0 0 0]
Second array 
 [[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]
Third array 
 [[0.33333333 0.33333333]
 [0.33333333 0.33333333]]
Fourth array 
 [ 0  4  8 12 16]
Fifth array 
 [0.         0.45454545 0.90909091 1.36363636 1.81818182 2.27272727
 2.72727273 3.18181818 3.63636364 4.09090909 4.54545455 5.        ]
Sixth array 
 [[0.17391567 0.87094768 0.28322216 0.37733994]
 [0.76331223 0.53541174 0.26511239 0.13980708]
 [0.84240737 0.05013796 0.85329252 0.68589305]
 [0.57077884 0.77108252 0.97385072 0.78054389]]
Seventh array 
 [[ 1.00790068 -0.92156688 -1.04422433]
 [ 0.36402478 -0.70796267  0.8132091 ]
 [-0.45330646  0.79233155 -0.78128127]]
Eighth array 
 [[21 21 22]
 [20 20 23]
 [21 24 20]]
Ninth array 
 [[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
Tenth array 
 [[4.67296746e-307 1.69121096e-306 9.34611148e-307 8.34441742e-308]
 [1.78022342e-306 6.23058028e-307 9.79107872e-307 6.89807188e-307]
 [7.565943

In [90]:
# Инициализация массивов
np.random.seed(0)
x1 = np.random.randint(10, size = 5)
x2 = np.random.randint(2,10, size = (5, 5))
x3 = np.random.randint(6,12, size = (5, 5, 5))
# Копирование и представление срезов
buf_1 = x3[:1, :, :].copy()
x3[0, 1, 2] = 777
# Работа с массивом
print('------------------')
print('Одномерный массив \n', x1)
print('Размерность: ', x1.ndim)
print('Размер каждого измерения: ', x1.shape)
print('Общий размер массива: ', x1.size)
print('Тип данных массива: ', x1.dtype)
print('Размер каждого элемента массива в байтах: ', x1.itemsize)
print('Размер массива в байтах: ', x1.nbytes, '\n')
print('Индексация массива:')
print('Третий элемент массива: ', x1[2], '\n')
print('Срезы массива:')
print('Каждый второй элемент: ', x1[1::2])
print('Все элементы, начиная со второго: ', x1[1::])
print('Все элементы, заканчивая четвертым: ', x1[:4:])
print('Массив наоборот: ', x1[::-1])
print('------------------')
print('Двумерный массив \n', x2)
print('Размерность: ', x2.ndim)
print('Размер каждого измерения: ', x2.shape)
print('Общий размер массива: ', x2.size)
print('Тип данных массива: ', x2.dtype)
print('Размер каждого элемента массива в байтах: ', x2.itemsize)
print('Размер массива в байтах: ', x2.nbytes, '\n')
print('Индексация массива:')
print('Элемент в первой строке второго столбца с конца: ', x2[0, -2], '\n')
print('------------------')
print('Трехмерный массив \n', x3)
print('Размерность: ', x3.ndim)
print('Размер каждого измерения: ', x3.shape)
print('Общий размер массива: ', x3.size)
print('Тип данных массива: ', x3.dtype)
print('Размер каждого элемента массива в байтах: ', x3.itemsize)
print('Размер массива в байтах: ', x3.nbytes, '\n')
print('Индексация массива:')
print('Переобозначенный первый элемент второй строки третьего блока ', x3[0, 1, 2], ' (было) ', buf_1[0, 1, 2], '\n')
print('Срезы массива:')
print('Три строки и два столбца первого блока:\n ', x3[0, :3, :2])
print('Две строки со всеми столбцами второго блока:\n ', x3[1, :2, :])
print('------------------')

------------------
Одномерный массив 
 [5 0 3 3 7]
Размерность:  1
Размер каждого измерения:  (5,)
Общий размер массива:  5
Тип данных массива:  int32
Размер каждого элемента массива в байтах:  4
Размер массива в байтах:  20 

Индексация массива:
Третий элемент массива:  3 

Срезы массива:
Каждый второй элемент:  [0 3]
Все элементы, начиная со второго:  [0 3 3 7]
Все элементы, заканчивая четвертым:  [5 0 3 3]
Массив наоборот:  [7 3 3 0 5]
------------------
Двумерный массив 
 [[3 5 7 4 6]
 [9 8 2 2 6]
 [4 3 8 9 9]
 [8 2 3 7 3]
 [7 2 3 6 5]]
Размерность:  2
Размер каждого измерения:  (5, 5)
Общий размер массива:  25
Тип данных массива:  int32
Размер каждого элемента массива в байтах:  4
Размер массива в байтах:  100 

Индексация массива:
Элемент в первой строке второго столбца с конца:  4 

------------------
Трехмерный массив 
 [[[  6   9  11   6   8]
  [  9   6 777   9  11]
  [  9   9   6   7   7]
  [  7   6   8  10   9]
  [  9   8  10   8   6]]

 [[  6  10  11  11   6]
  [ 10   7  10

In [110]:
x4 = np.array([i for i in range(3)])
print(x4)
print('----------')
x4 = x4.reshape((1,3))
print(x4)
x4 = np.array([i for i in range(3)])
x4 = x4.reshape((3,1))
print(x4)
print('----------')
x4 = np.array([i for i in range(3)])
x4 = x4[np.newaxis, :]
print(x4)
x4 = np.array([i for i in range(3)])
x4 = x4[:, np.newaxis]
print(x4)
print('----------')
grid = np.arange(1,10).reshape((3,3))
print(grid)

[0 1 2]
----------
[[0 1 2]]
[[0]
 [1]
 [2]]
----------
[[0 1 2]]
[[0]
 [1]
 [2]]
----------
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
np.random.seed(0)
dim = (2,2)
x1 = np.random.randint(5, size = dim)
print(x1)
x2 = np.random.randint(5, size = dim)
print(x2)
x3 = np.random.randint(5, size = 2)
print(x3)
x4 = np.random.randint(5, size = 2)
x4 = x4[:, np.newaxis]
print(x4)

[[4 0]
 [3 3]]
[[3 1]
 [3 2]]
[4 0]
[[0]
 [4]]


In [7]:
# слияние массивов 
cc1 = np.concatenate([x1,x2], axis = 0)
cc2 = np.concatenate([x1,x2], axis = 1)
cc3 = np.vstack([x1,x3])
cc4 = np.hstack([x1,x4])
print(cc1)
print(cc2)
print(cc3)
print(cc4)
sp1, sp2, sp3 = np.hsplit(cc4, [1,2])
print(sp1, sp2, sp3)

[[4 0]
 [3 3]
 [3 1]
 [3 2]]
[[4 0 3 1]
 [3 3 3 2]]
[[4 0]
 [3 3]
 [4 0]]
[[4 0 0]
 [3 3 4]]
[[4]
 [3]] [[0]
 [3]] [[0]
 [4]]
