In [43]:
import numpy as np
from scipy import special as sp

In [2]:
def div1 (mass):
    out_mass = np.zeros(shape = mass.shape)
    for i in range(mass.shape[0]):
        for j in range(mass.shape[1]):
            out_mass[i][j] = 1/mass[i][j]
    return out_mass

In [3]:
np.random.seed(0)
dim = (50,50)
x1 = np.random.random(dim)
print(x0)
%timeit div1(x0)
%timeit 1.0/x0

[[0.5488135  0.71518937 0.60276338 ... 0.1289263  0.31542835 0.36371077]
 [0.57019677 0.43860151 0.98837384 ... 0.02010755 0.82894003 0.00469548]
 [0.67781654 0.27000797 0.73519402 ... 0.91948261 0.7142413  0.99884701]
 ...
 [0.0698143  0.22649128 0.48110196 ... 0.43584121 0.73859222 0.52658426]
 [0.88668322 0.8309088  0.03160544 ... 0.55957053 0.5846446  0.09127072]
 [0.60047104 0.38152221 0.86758085 ... 0.72433098 0.19157101 0.66217423]]
1.87 ms ± 17.1 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [25]:
x1 = np.linspace(start = 0, stop = np.pi * 2, num = 20)
y1 = np.zeros(shape = x1.shape)
print(x1)
print(np.exp(x1))
print(np.cos(x1))
print(np.arctan(x1))
np.expm1(x1, out = y1);
print(y1)
print(sp.erf(x1))
print(np.add.reduce(x1))
print(np.add.accumulate(x1))

[0.         0.33069396 0.66138793 0.99208189 1.32277585 1.65346982
 1.98416378 2.31485774 2.64555171 2.97624567 3.30693964 3.6376336
 3.96832756 4.29902153 4.62971549 4.96040945 5.29110342 5.62179738
 5.95249134 6.28318531]
[  1.           1.39193374   1.93747955   2.69684316   3.753827
   5.22507848   7.27296305  10.1234827   14.09121718  19.6140407
  27.30144511  38.00180273  52.89599158  73.62771563 102.48490193
 142.65219331 198.56240162 276.38570723 384.71059243 535.49165552]
[ 1.          0.94581724  0.78914051  0.54694816  0.24548549 -0.08257935
 -0.40169542 -0.67728157 -0.87947375 -0.9863613  -0.9863613  -0.87947375
 -0.67728157 -0.40169542 -0.08257935  0.24548549  0.54694816  0.78914051
  0.94581724  1.        ]
[0.         0.31937324 0.58433918 0.78142339 0.92347519 1.0268631
 1.10396129 1.16301834 1.20940425 1.24665329 1.27714429 1.30251938
 1.32394059 1.34224947 1.35806837 1.37186637 1.3840031  1.39475853
 1.40435366 1.41296514]
[0.00000000e+00 3.91933745e-01 9.37479549e-01

In [42]:
x2 = np.arange(0, 5, 1)
#x2_0 = np.zeros(shape = x2.shape)
print(x2)
x2_0 = np.multiply.outer(x2, x2)
print(x2_0)
print(np.add.outer(x2, x2))
x3 = np.arange(0, 4).reshape(2, 2)
print(x3)
print(np.add.outer(x2, x3))
print(x3.min())
print(x2_0.max(axis = 1))

[0 1 2 3 4]
[[ 0  0  0  0  0]
 [ 0  1  2  3  4]
 [ 0  2  4  6  8]
 [ 0  3  6  9 12]
 [ 0  4  8 12 16]]
[[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]]
[[0 1]
 [2 3]]
[[[0 1]
  [2 3]]

 [[1 2]
  [3 4]]

 [[2 3]
  [4 5]]

 [[3 4]
  [5 6]]

 [[4 5]
  [6 7]]]
0
[ 0  4  8 12 16]


In [62]:
# Транслирование массивов
x = np.arange(3)
y = np.arange(3)
print(x)
print(y)
print('--------')
print(x + 5)
print(x * 2)
print('--------')
print(x + y)
print(np.add(x, y))
print(np.add.outer(x,y))
print('--------')
y = y[:, np.newaxis]
print(y)
print(x + y)
print(np.add.outer(x, y))
print('--------')
k = np.arange(9).reshape(3,3)
l = np.arange(3)
print(k + l)

[0 1 2]
[0 1 2]
--------
[5 6 7]
[0 2 4]
--------
[0 2 4]
[0 2 4]
[[0 1 2]
 [1 2 3]
 [2 3 4]]
--------
[[0]
 [1]
 [2]]
[[0 1 2]
 [1 2 3]
 [2 3 4]]
[[[0]
  [1]
  [2]]

 [[1]
  [2]
  [3]]

 [[2]
  [3]
  [4]]]
--------
[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]]
