In [25]:
import pandas as pd
import numpy as np

In [22]:
i = range(5)
ind = pd.Index(i) - 3
data_0 = pd.Series(np.random.random(ind.size), index = ind)
print(data_0)
print(data_0.loc[0:2]) #явная индексация
print(data_0.iloc[0:2]) #неявная индексация

-3    0.770303
-2    0.397057
-1    0.319561
0     0.527126
1     0.570809
dtype: float64
0    0.527126
1    0.570809
dtype: float64
-3    0.770303
-2    0.397057
dtype: float64


In [30]:
population_dict = {'Moscow': 12197596,
                  'St.Petersburg': 5191690,
                  'Novosibirsk': 1567087,
                  'Ekaterinburg': 1428042,
                  'Nizhnii Novgorod': 1267760}
population = pd.Series(population_dict)
area_dict = {'Moscow': 2561,
            'St.Petersburg': 1439,
            'Novosibirsk': 502,
            'Ekaterinburg': 468,
            'Nizhnii Novgorod': 466}
area = pd.Series(area_dict)

In [38]:
#как словарь
stat_cities = pd.DataFrame({'population': population, 'area': area})
stat_cities['density'] = stat_cities['population'] / stat_cities['area']
print(stat_cities)

                  population  area      density
Moscow              12197596  2561  4762.825459
St.Petersburg        5191690  1439  3607.845726
Novosibirsk          1567087   502  3121.687251
Ekaterinburg         1428042   468  3051.371795
Nizhnii Novgorod     1267760   466  2720.515021


In [48]:
#как массив
print(stat_cities.values)
print(stat_cities.T)
print(stat_cities.values[0])
print(stat_cities.loc[:'Novosibirsk', :'area'])
print(stat_cities.iloc[0:4:2, :2])
#print(stat_cities.ix[0:4:2, :'area']) #устаревший метод
print(stat_cities.loc[stat_cities.density > 3100, ['population', 'area']])

[[1.21975960e+07 2.56100000e+03 4.76282546e+03]
 [5.19169000e+06 1.43900000e+03 3.60784573e+03]
 [1.56708700e+06 5.02000000e+02 3.12168725e+03]
 [1.42804200e+06 4.68000000e+02 3.05137179e+03]
 [1.26776000e+06 4.66000000e+02 2.72051502e+03]]
                  Moscow  St.Petersburg   Novosibirsk  Ekaterinburg  \
population  1.219760e+07   5.191690e+06  1.567087e+06  1.428042e+06   
area        2.561000e+03   1.439000e+03  5.020000e+02  4.680000e+02   
density     4.762825e+03   3.607846e+03  3.121687e+03  3.051372e+03   

            Nizhnii Novgorod  
population      1.267760e+06  
area            4.660000e+02  
density         2.720515e+03  
[1.21975960e+07 2.56100000e+03 4.76282546e+03]
               population  area
Moscow           12197596  2561
St.Petersburg     5191690  1439
Novosibirsk       1567087   502
             population  area
Moscow         12197596  2561
Novosibirsk     1567087   502
               population  area
Moscow           12197596  2561
St.Petersburg     519